version: '3'
services:
  redis-server:
    image: redis
    ports:
     - "6379:6379"
  node-app:
    image: deinmaarnix/exam:latest
    ports:
     - "8001:8081"
    depends_on:
     - "redis-server"   
