version: '3'
services:
  redis-server:
    image: redis
    ports:
     - "6379:6379"
  node-app:
    image: deinmaarnix/{{JOB_NAME}}:{{BUILD_NUMBER}}
    ports:
     - "8{{BUILD_NUMBER}}:8081"
    depends_on:
     - "redis-server"   
