- name: install and run containers
  hosts: webservers
  tasks:
  - name: install packages
    yum:
      name: 
        - yum-utils
        - python3-pip
      state: present
  - name: "Configuring docker-ce repo"
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644
  - name: install docker
    yum:
      name: docker-ce
      state: present
  - name: start docker daemon
    service:
      name: docker
      state: started
      enabled: true
  - name: install docker module
    pip:
      name: docker
  - name: copy docker-compose binary
    copy:
      src: ./docker-compose
      dest: /usr/local/bin/docker-compose
      owner: root
      group: root
      mode: 0777
  - name: copy docker-compose.yaml
    copy:
      src: ./docker-compose.yml
      dest: /home/ansible/docker-compose.yml
      owner: ansible
      group: ansible
      mode: 0644
  - name: 
    command:
       cmd: /usr/local/bin/docker-compose -f /home/ansible/docker-compose.yml  up -d  
  - name: open firewalld
    firewalld:
      port: 8001/tcp
      permanent: yes
      state: enabled
      immediate: yes

